### ISSUE TITLE
Unhandled ETIMEDOUT error crashes process

### ISSUE THREAD

**Issue by justinmchase** [mikael-lindstrom/amazon-elasticsearch-proxy#3]
This isn't a huge deal but if my laptop falls asleep or I move from router to router the connection can fail and crash the process.

It would be pretty nice if this case was just handled and retried in a loop without crashing the process. Here is the error output:

```
Error: Error: connect ETIMEDOUT <ip>:443
/Users/justin/.nvm/versions/node/v9.2.0/lib/node_modules/amazon-elasticsearch-proxy/proxy.js:71
          next(err, respBody);
                    ^

ReferenceError: respBody is not defined
    at ClientRequest.<anonymous> (/Users/justin/.nvm/versions/node/v9.2.0/lib/node_modules/amazon-elasticsearch-proxy/proxy.js:71:21)
    at ClientRequest.<anonymous> (/Users/justin/.nvm/versions/node/v9.2.0/lib/node_modules/amazon-elasticsearch-proxy/node_modules/aws-sdk/lib/http/node.js:89:19)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by mikael-lindstrom** [comment]
I updated the proxy to instead of crashing log the error and return `503 Service Unavailable` if the network connections is lost. Once the connection is established again the proxy continues working.

Push release 0.1.4 to npm, let me know if you run into any problems.

**Comment by justinmchase** [comment]
It worked. I came into work and opened my laptop and there were some errors printed but my kibana tab just auto-refreshed and was good to go.

👍
