### ISSUE TITLE
No Method startsWith

### ISSUE THREAD

**Issue by nsaud01** [mikael-lindstrom/amazon-elasticsearch-proxy#5]
Having an issue running this in docker. I'm getting the following error:

```
/usr/local/lib/node_modules/amazon-elasticsearch-proxy/cli.js:18
if (commander.args[0].startsWith('https://')) {
                      ^
TypeError: Object search-foobar-east-1.es.amazonaws.com has no method 'startsWith'
    at Object.<anonymous> (/usr/local/lib/node_modules/amazon-elasticsearch-proxy/cli.js:18:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by mikael-lindstrom** [comment]
I suspect this is related to nodejs version, which version are you using?
Could you post the Dockerfile?

**Comment by nsaud01** [comment]
You're right. Once downgrading to node 4, the issue was gone. Hopefully amazon-elasticsearch-proxy can support later node versions as well. Thanks @mikael-lindstrom. I'll close this issue.
